#ifndef INC_3_RD_SEMESTER_CPP_PROJECT_GAMEPLAYHANDLING_HPP
#define INC_3_RD_SEMESTER_CPP_PROJECT_GAMEPLAYHANDLING_HPP

inline volatile bool gameplayElementLock = false;

void HandleGameplay();

#endif //INC_3_RD_SEMESTER_CPP_PROJECT_GAMEPLAYHANDLING_HPP
